package com.example.ui.util

import androidx.compose.runtime.staticCompositionLocalOf

data class AppStrings(
    val langCode: String,
    val home: String,
    val products: String,
    val sales: String,
    val customers: String,
    val reports: String,
    val settings: String,
    val welcomeBack: String,
    val todaySales: String,
    val todayExpenses: String,
    val todayProfit: String,
    val quickActions: String,
    val newSale: String,
    val addProduct: String,
    val recentActivity: String,
    val viewAll: String,
    val noRecentSales: String,
    val lowStockAlert: String,
    val languageSetting: String,
    val languageSubtitle: String,
    val english: String,
    val amharic: String,
    val businessIdentity: String,
    val businessName: String,
    val businessLogo: String,
    val currencySymbol: String,
    val appearanceTheme: String,
    val systemDefault: String,
    val lightMode: String,
    val darkMode: String,
    val saveSettings: String,
    val logExpense: String,
    val daily: String,
    val weekly: String,
    val monthly: String,
    val totalSales: String,
    val totalExpenses: String,
    val netProfit: String,
    val productsSold: String,
    val remainingStock: String,
    val salesVsExpenses: String,
    val topSellingProducts: String,
    val salesInPeriod: String,
    val noSalesInPeriod: String,
    val emailReport: String,
    val saveExcel: String,
    val shareExcel: String,
    val excelReportReady: String,
    val sendEmail: String,
    val recipientEmail: String,
    val emailSubject: String,
    val attachExcel: String,
    val copySummary: String,
    val openInExcel: String,
    val saveToDevice: String,
    val cancel: String,
    val exportAndShare: String,
    val autoReport: String,
    val autoReportSubtitle: String,
    val autoReportStatusOn: String,
    val autoReportStatusOff: String,
    val frequency: String,
    val reportFormat: String,
    val autoReportEmail: String,
    val testAutoReport: String,
    val on: String,
    val off: String,
    val transactionsCount: (Int) -> String,
    val expensesCount: (Int) -> String,
    val unitsSold: (Int) -> String
)

val EnglishStrings = AppStrings(
    langCode = "en",
    home = "Home",
    products = "Products",
    sales = "Sales",
    customers = "Customers",
    reports = "Reports",
    settings = "Settings",
    welcomeBack = "Welcome back! ✨",
    todaySales = "Today's Sales",
    todayExpenses = "Today's Expenses",
    todayProfit = "Today's Profit",
    quickActions = "Quick Actions",
    newSale = "New Sale",
    addProduct = "Add Product",
    recentActivity = "Recent Sales Activity",
    viewAll = "View All",
    noRecentSales = "No sales recorded yet today.",
    lowStockAlert = "Low Stock Alert ⚠️",
    languageSetting = "Language / ቋንቋ",
    languageSubtitle = "Choose your preferred display language",
    english = "English",
    amharic = "አማርኛ (Amharic)",
    businessIdentity = "Business Identity",
    businessName = "Business Name",
    businessLogo = "Business Logo / Mascot:",
    currencySymbol = "Currency Symbol",
    appearanceTheme = "Appearance Theme",
    systemDefault = "System Default",
    lightMode = "Cute Light Mode",
    darkMode = "Cozy Dark Mode",
    saveSettings = "Save Settings ✨",
    logExpense = "Log Operating Expense",
    daily = "Daily",
    weekly = "Weekly",
    monthly = "Monthly",
    totalSales = "Total Sales",
    totalExpenses = "Total Expenses",
    netProfit = "Net Profit",
    productsSold = "Products Sold",
    remainingStock = "still in stock",
    salesVsExpenses = "Sales vs Expenses 📊",
    topSellingProducts = "Top Selling Products 🏆",
    salesInPeriod = "Sales in this Period",
    noSalesInPeriod = "No sales in this period yet.",
    emailReport = "Email Report ✉️",
    saveExcel = "Save Excel (.xlsx) 📊",
    shareExcel = "Share Excel",
    excelReportReady = "Excel Report Generated!",
    sendEmail = "Send via Email App",
    recipientEmail = "Recipient Email",
    emailSubject = "Email Subject",
    attachExcel = "Attach Excel spreadsheet (.xlsx)",
    copySummary = "Copy Summary",
    openInExcel = "Open in Excel / Sheets",
    saveToDevice = "Save to Device Storage",
    cancel = "Cancel",
    exportAndShare = "Export & Reports Sharing",
    autoReport = "Auto Report (Automated Dispatch)",
    autoReportSubtitle = "Automatically generate & email reports on schedule",
    autoReportStatusOn = "Auto Report: ON ⚡",
    autoReportStatusOff = "Auto Report: OFF 💤",
    frequency = "Dispatch Frequency",
    reportFormat = "Default Format",
    autoReportEmail = "Destination Email (Accountant / Owner)",
    testAutoReport = "Test / Dispatch Now 🚀",
    on = "ON",
    off = "OFF",
    transactionsCount = { "$it transactions" },
    expensesCount = { "$it expense entries" },
    unitsSold = { "$it units sold" }
)

val AmharicStrings = AppStrings(
    langCode = "am",
    home = "መነሻ",
    products = "ምርቶች",
    sales = "ሽያጮች",
    customers = "ደንበኞች",
    reports = "ሪፖርቶች",
    settings = "ቅንብሮች",
    welcomeBack = "እንኳን ደህና መጡ! ✨",
    todaySales = "የዛሬ ሽያጭ",
    todayExpenses = "የዛሬ ወጪዎች",
    todayProfit = "የዛሬ ትርፍ",
    quickActions = "ፈጣን ተግባራት",
    newSale = "አዲስ ሽያጭ",
    addProduct = "እቃ መዝግብ",
    recentActivity = "የቅርብ ጊዜ ሽያጮች",
    viewAll = "ሁሉንም እይ",
    noRecentSales = "ዛሬ የተመዘገበ ሽያጭ የለም።",
    lowStockAlert = "ሊያልቅ የተቃረበ እቃ ⚠️",
    languageSetting = "ቋንቋ (Language)",
    languageSubtitle = "የመተግበሪያውን ቋንቋ ይምረጡ",
    english = "English (እንግሊዝኛ)",
    amharic = "አማርኛ (Amharic)",
    businessIdentity = "የንግድ መረጃ",
    businessName = "የንግድ ስም",
    businessLogo = "የንግድ አርማ / ምስል:",
    currencySymbol = "የገንዘብ ምልክት (Currency)",
    appearanceTheme = "የመተግበሪያ ገጽታ",
    systemDefault = "የስልኩ ነባሪ",
    lightMode = "ብሩህ ገጽታ",
    darkMode = "ጨለማ ገጽታ",
    saveSettings = "ቅንብሮችን አስቀምጥ ✨",
    logExpense = "ወጪ መዝግብ",
    daily = "የቀን",
    weekly = "የሳምንት",
    monthly = "የወር",
    totalSales = "ጠቅላላ ሽያጭ",
    totalExpenses = "ጠቅላላ ወጪ",
    netProfit = "የተጣራ ትርፍ",
    productsSold = "የተሸጡ ምርቶች",
    remainingStock = "በመጋዘን የቀረ",
    salesVsExpenses = "ሽያጭ እና ወጪ 📊",
    topSellingProducts = "በብዛት የተሸጡ ምርቶች 🏆",
    salesInPeriod = "በዚህ ጊዜ የተደረጉ ሽያጮች",
    noSalesInPeriod = "በዚህ ጊዜ ምንም ሽያጭ የለም።",
    emailReport = "ሪፖርቱን በኢሜይል ላክ ✉️",
    saveExcel = "በExcel (.xlsx) አስቀምጥ 📊",
    shareExcel = "የExcel ፋይል አጋራ",
    excelReportReady = "የExcel ሪፖርት ተዘጋጅቷል!",
    sendEmail = "በኢሜይል ላክ",
    recipientEmail = "የተቀባይ ኢሜይል አድራሻ",
    emailSubject = "የኢሜይል ርዕስ",
    attachExcel = "የExcel ፋይል (.xlsx) አያይዝ",
    copySummary = "ጽሁፉን ቅዳ",
    openInExcel = "በExcel / Sheets ክፈት",
    saveToDevice = "ወደ ስልክ ማከማቻ አስቀምጥ",
    cancel = "ሰርዝ",
    exportAndShare = "ሪፖርት ማውጣትና ማጋራት",
    autoReport = "ራስ-ሰር ሪፖርት (Auto Report)",
    autoReportSubtitle = "ሪፖርቶችን በራስ-ሰር ያዘጋጁ እና በኢሜይል ይላኩ",
    autoReportStatusOn = "ራስ-ሰር ሪፖርት: በርቷል ⚡",
    autoReportStatusOff = "ራስ-ሰር ሪፖርት: ጠፍቷል 💤",
    frequency = "የመላኪያ ድግግሞሽ",
    reportFormat = "የሪፖርት ቅርጸት",
    autoReportEmail = "የተቀባይ ኢሜይል (ባለቤት / አካውንታንት)",
    testAutoReport = "አሁን ሞክር / ሪፖርቱን ላክ 🚀",
    on = "በርቷል",
    off = "ጠፍቷል",
    transactionsCount = { "$it ሽያጮች" },
    expensesCount = { "$it ወጪዎች" },
    unitsSold = { "$it እቃዎች ተሽጠዋል" }
)

val LocalStrings = staticCompositionLocalOf { EnglishStrings }

fun getAppStrings(languageCode: String): AppStrings {
    return if (languageCode == "am") AmharicStrings else EnglishStrings
}
